#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/uke

PRODUCT_COPY_FILES += \
    vendor/xiaomi/uke/proprietary/odm/etc/acdbdata/Forte/Forte_acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Forte/Forte_acdb_cal.acdb \
    vendor/xiaomi/uke/proprietary/odm/etc/acdbdata/Forte/Forte_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Forte/Forte_workspaceFileXml.qwsp \
    vendor/xiaomi/uke/proprietary/odm/etc/audio-test-config:$(TARGET_COPY_OUT_ODM)/etc/audio-test-config \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/RES1K.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/RES1K.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/bl-spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/bl-spk.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/bl-spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/bl-spk_hp.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/br-spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/br-spk.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/br-spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/br-spk_hp.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/mis_head.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/mis_head.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/mis_head_spatial.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/mis_head_spatial.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/mis_spk.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/mis_spk.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/mis_spk_spatial.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/mis_spk_spatial.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/misound_karaoke_res.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_karaoke_res.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/misound_karaokemix_res.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_karaokemix_res.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/misound_res_spk_power_game.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_res_spk_power_game.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/misound_res_spk_power_game_powersave.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_res_spk_power_game_powersave.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/misound_res_spk_power_sva.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_res_spk_power_sva.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/misound_res_spk_power_sva_powersave.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_res_spk_power_sva_powersave.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/misound_res_spk_power_video.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_res_spk_power_video.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/misound_res_spk_power_video_powersave.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_res_spk_power_video_powersave.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/misoundsa_spk_config.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misoundsa_spk_config.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/rcv.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/rcv.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/rcv_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/rcv_hp.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/rcv_seal.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/rcv_seal.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/sku_cliffs/mixer_paths_overlay_static.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_cliffs/mixer_paths_overlay_static.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/sku_cliffs/resourcemanager_cliffs_mtp.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_cliffs/resourcemanager_cliffs_mtp.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/sku_cliffs_qssi/audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_cliffs_qssi/audio_policy_configuration.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/spk.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/spk_cal_silence.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/spk_cal_silence.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/spk_dsm_test.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/spk_dsm_test.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/spk_hp.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/test.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/test.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/tl-spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tl-spk.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/tl-spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tl-spk_hp.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/tr-spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tr-spk.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio/tr-spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tr-spk_hp.wav \
    vendor/xiaomi/uke/proprietary/odm/etc/audio_game_effect_items.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_game_effect_items.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/audio_policy_engine_configuration_mi.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_engine_configuration_mi.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/audio_policy_engine_stream_volumes.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_engine_stream_volumes.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/buling_1s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_1s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/buling_2s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_2s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/buling_3s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_3s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/buling_4s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_4s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/buling_5s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_5s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/circle_1.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_1.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/circle_2.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_2.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/circle_3.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_3.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/circle_4.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_4.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/circle_5.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_5.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/circle_6.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_6.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/clip_1.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_1.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/clip_2.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_2.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/clip_3.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_3.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/clip_4.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_4.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/clip_5.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_5.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/clip_6.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_6.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/clip_7.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_7.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/heart_1s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_1s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/heart_2s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_2s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/heart_3s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_3s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/heart_4s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_4s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/heart_5s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_5s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/heart_6s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_6s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/AIGesture/thumbup_3s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/thumbup_3s.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/CFR_para_MACRO_V01.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_MACRO_V01.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/CFR_para_MACRO_V01_SN.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_MACRO_V01_SN.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/CFR_para_T_2x_V01.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_T_2x_V01.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/CFR_para_UW_V01.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_UW_V01.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/CFR_para_UW_V01_SN.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_UW_V01_SN.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/CFR_para_W_V01.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_W_V01.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/CFR_para_W_V01_HD.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_W_V01_HD.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/CFR_para_W_V01_IZOOM.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_W_V01_IZOOM.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/CFR_para_W_V01_SN.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_W_V01_SN.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_ODM)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_class_all.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_class_all.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_class_human.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_class_human.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_classify.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_classify.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_detect.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_detect.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_detect_1st.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_detect_1st.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_detect_2nd.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_detect_2nd.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_detect_3rd.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_detect_3rd.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_saliency.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_saliency.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_track_backbone.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_track_backbone.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_track_head.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_track_head.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/IntellFocus_track_rpn.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/IntellFocus_track_rpn.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/SensePR_scene_configs.json:$(TARGET_COPY_OUT_ODM)/etc/camera/SensePR_scene_configs.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/af_class_all.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/af_class_all.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/af_class_human.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/af_class_human.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/af_classify.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/af_classify.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/af_detect_1st.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/af_detect_1st.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/af_detect_2nd.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/af_detect_2nd.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/af_detect_3rd.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/af_detect_3rd.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/af_saliency.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/af_saliency.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/af_track_backbone.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/af_track_backbone.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/af_track_head.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/af_track_head.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/aivsModel_168C0E45:$(TARGET_COPY_OUT_ODM)/etc/camera/aivsModel_168C0E45 \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/aivsModel_16E8F8F9:$(TARGET_COPY_OUT_ODM)/etc/camera/aivsModel_16E8F8F9 \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/aivsModel_20D4BB1D:$(TARGET_COPY_OUT_ODM)/etc/camera/aivsModel_20D4BB1D \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/aivsModel_298FD264:$(TARGET_COPY_OUT_ODM)/etc/camera/aivsModel_298FD264 \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/alCFR_Segmodel.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/alCFR_Segmodel.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/altekldc_tuningdata.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/altekldc_tuningdata.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/arcsoft_dynamicEV_config.ini:$(TARGET_COPY_OUT_ODM)/etc/camera/arcsoft_dynamicEV_config.ini \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/arcsoft_turbohdr_dynamicEV_config.ini:$(TARGET_COPY_OUT_ODM)/etc/camera/arcsoft_turbohdr_dynamicEV_config.ini \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/beauty_config_cn.json:$(TARGET_COPY_OUT_ODM)/etc/camera/beauty_config_cn.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/beauty_config_cn_8g.json:$(TARGET_COPY_OUT_ODM)/etc/camera/beauty_config_cn_8g.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/beauty_config_gl.json:$(TARGET_COPY_OUT_ODM)/etc/camera/beauty_config_gl.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/beauty_config_gl_8g.json:$(TARGET_COPY_OUT_ODM)/etc/camera/beauty_config_gl_8g.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/cameradfx_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/cameradfx_config.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/cameraopt_reclaim.json:$(TARGET_COPY_OUT_ODM)/etc/camera/cameraopt_reclaim.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/camxoverridesettings.txt \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/deblur_txt_dsp.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/deblur_txt_dsp.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/deblur_txt_gpu.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/deblur_txt_gpu.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/dlengine.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/dlengine.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/enhance_motiontuning.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/enhance_motiontuning.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/Vega_Attribute_Face_RGB_1.24.7_fp16_arm64.model:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/Vega_Attribute_Face_RGB_1.24.7_fp16_arm64.model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/Vega_Detect.model:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/Vega_Detect.model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/Vega_Detect_Sculpture.model:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/Vega_Detect_Sculpture.model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/detlmk.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/detlmk.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/facedet_dark_full.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_dark_full.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/facedet_dark_part.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_dark_part.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/facedet_front.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_front.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/facedet_full.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_full.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/facedet_part.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_part.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facefocus_models/facevalid.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facevalid.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/facesr_hd_composite_ff_hd_5.18.7_qcom7675_qnn_segqnn_hd0825YQuantQnn2.24.0.model:$(TARGET_COPY_OUT_ODM)/etc/camera/facesr_hd_composite_ff_hd_5.18.7_qcom7675_qnn_segqnn_hd0825YQuantQnn2.24.0.model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/hdrcheckerextendparamsettings.yml:$(TARGET_COPY_OUT_ODM)/etc/camera/hdrcheckerextendparamsettings.yml \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/hdrcheckerparamsettings.yml:$(TARGET_COPY_OUT_ODM)/etc/camera/hdrcheckerparamsettings.yml \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/immunesystem_hook_case.json:$(TARGET_COPY_OUT_ODM)/etc/camera/immunesystem_hook_case.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/intsense_config_singlebokeh.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/intsense_config_singlebokeh.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/itt_class_all.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/itt_class_all.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/itt_classify.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/itt_classify.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/itt_detect_1st.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/itt_detect_1st.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/itt_track_backbone.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/itt_track_backbone.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/itt_track_head.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/itt_track_head.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/jiiganLdcFront/ldc_cap_cache:$(TARGET_COPY_OUT_ODM)/etc/camera/jiiganLdcFront/ldc_cap_cache \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/jiiganLdcFront/ldc_cap_model:$(TARGET_COPY_OUT_ODM)/etc/camera/jiiganLdcFront/ldc_cap_model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/jiiganLdcFront/ldc_cap_policy:$(TARGET_COPY_OUT_ODM)/etc/camera/jiiganLdcFront/ldc_cap_policy \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/jiiganLdcUW/ldc_cap_cache:$(TARGET_COPY_OUT_ODM)/etc/camera/jiiganLdcUW/ldc_cap_cache \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/jiiganLdcUW/ldc_cap_model:$(TARGET_COPY_OUT_ODM)/etc/camera/jiiganLdcUW/ldc_cap_model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/jiiganLdcUW/ldc_cap_policy:$(TARGET_COPY_OUT_ODM)/etc/camera/jiiganLdcUW/ldc_cap_policy \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/jiiganLdcWide/ldc_cap_cache:$(TARGET_COPY_OUT_ODM)/etc/camera/jiiganLdcWide/ldc_cap_cache \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/jiiganLdcWide/ldc_cap_model:$(TARGET_COPY_OUT_ODM)/etc/camera/jiiganLdcWide/ldc_cap_model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/jiiganLdcWide/ldc_cap_policy:$(TARGET_COPY_OUT_ODM)/etc/camera/jiiganLdcWide/ldc_cap_policy \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/libarcsoft_high_dynamic_range.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/libarcsoft_high_dynamic_range.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/libarcsoft_mf_superresolution.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/libarcsoft_mf_superresolution.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/miasd_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/miasd_config.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/mihal_overlap/overlap_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/mihal_overlap/overlap_config.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/mihal_overlap/proj_overlap_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/mihal_overlap/proj_overlap_config.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/mimotion_f3b.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/mimotion_f3b.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/mimotion_f3w.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/mimotion_f3w.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/mimotion_f4b.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/mimotion_f4b.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/mimotion_f4w.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/mimotion_f4w.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/mimotion_f5b.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/mimotion_f5b.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/mimotion_f5w.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/mimotion_f5w.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/misoverridesettings.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/misoverridesettings.txt \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/model.data:$(TARGET_COPY_OUT_ODM)/etc/camera/model.data \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/model_ai_dxo.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_ai_dxo.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/model_aiie_cap.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_aiie_cap.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_back.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_front.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/model_glass.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_glass.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/model_indoor.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_indoor.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/motiontuning.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/motiontuning.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/night_motiontuning.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/night_motiontuning.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_0_again_small10_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_0_again_small10_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_1_again_large10_small25_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_1_again_large10_small25_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_2_again_large25_small40_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_2_again_large25_small40_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_3_again_large40_small50_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_3_again_large40_small50_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_4_again_large50_small64_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_4_again_large50_small64_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_5_again_dark_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_jg/dcg_jg_ainr_5_again_dark_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_xm/dcg_xm_ainr_1_again_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_xm/dcg_xm_ainr_1_again_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_xm/dcg_xm_ainr_2_again_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_xm/dcg_xm_ainr_2_again_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_xm/dcg_xm_ainr_3_again_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_xm/dcg_xm_ainr_3_again_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_xm/nonhdr_xm_ainr_1_again_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_xm/nonhdr_xm_ainr_1_again_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_xm/nonhdr_xm_ainr_2_again_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_xm/nonhdr_xm_ainr_2_again_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dcg/ainr_xm/nonhdr_xm_ainr_3_again_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dcg/ainr_xm/nonhdr_xm_ainr_3_again_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/depth/depth_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/depth/depth_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/depth/seg_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/depth/seg_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_0_again_small10_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_0_again_small10_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_1_again_large10_small25_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_1_again_large10_small25_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_2_again_large25_small40_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_2_again_large25_small40_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_3_again_large40_small50_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_3_again_large40_small50_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_4_again_large50_small64_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_4_again_large50_small64_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_5_again_dark_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dol/ainr_jg/dol_jg_ainr_5_again_dark_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dol/ainr_xm/dol_xm_hdr_ainr_again_all_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dol/ainr_xm/dol_xm_hdr_ainr_again_all_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dol/ainr_xm/dol_xm_nonhdr_ainr_0_again_normal_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dol/ainr_xm/dol_xm_nonhdr_ainr_0_again_normal_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/dol/ainr_xm/dol_xm_nonhdr_ainr_1_again_dark_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/dol/ainr_xm/dol_xm_nonhdr_ainr_1_again_dark_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_fa_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_fa_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_fd_front_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_fd_front_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_fd_rear_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_fd_rear_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_pre_360_0_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_pre_360_0_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_pre_360_180_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_pre_360_180_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_pre_360_270_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_pre_360_270_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_pre_360_90_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_pre_360_90_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_pre_480_0_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_pre_480_0_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_pre_480_180_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_pre_480_180_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_pre_480_270_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_pre_480_270_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/npu_model/face/face_pre_480_90_model.nb:$(TARGET_COPY_OUT_ODM)/etc/camera/npu_model/face/face_pre_480_90_model.nb \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/ocr_aio:$(TARGET_COPY_OUT_ODM)/etc/camera/ocr_aio \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/TStools_default_param.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/TStools_default_param.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/Version.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/Version.txt \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/default_param.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/default_param.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/model/2722133617:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/model/2722133617 \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/Material/1166466556_252005700:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/Material/1166466556_252005700 \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/Material/1166466556_2571257293:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/Material/1166466556_2571257293 \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/Material/1166466556_4025145477:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/Material/1166466556_4025145477 \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_BASE.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_BASE.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_COLOR_LAYER_WITH_MASK_Define_NORMAL_MASK_CHANNEL_TYPE_R_FRAMEBUFFER_FETCH_ADRENO.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_COLOR_LAYER_WITH_MASK_Define_NORMAL_MASK_CHANNEL_TYPE_R_FRAMEBUFFER_FETCH_ADRENO.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_IMAGE_LAYER_Define_MULTIPLY_FRAMEBUFFER_FETCH_ADRENO.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_IMAGE_LAYER_Define_MULTIPLY_FRAMEBUFFER_FETCH_ADRENO.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_IMAGE_LAYER_Define_SOFT_LIGHT_FRAMEBUFFER_FETCH_ADRENO.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_IMAGE_LAYER_Define_SOFT_LIGHT_FRAMEBUFFER_FETCH_ADRENO.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_IMAGE_LAYER_WITH_MASK_Define_MULTIPLY_MASK_CHANNEL_TYPE_R_FRAMEBUFFER_FETCH_ADRENO.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_IMAGE_LAYER_WITH_MASK_Define_MULTIPLY_MASK_CHANNEL_TYPE_R_FRAMEBUFFER_FETCH_ADRENO.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_IMAGE_LAYER_WITH_MASK_Define_SOFT_LIGHT_MASK_CHANNEL_TYPE_R_FRAMEBUFFER_FETCH_ADRENO.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_BLEND_IMAGE_LAYER_WITH_MASK_Define_SOFT_LIGHT_MASK_CHANNEL_TYPE_R_FRAMEBUFFER_FETCH_ADRENO.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_BRIGHT_EYE_PROCESS.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_BRIGHT_EYE_PROCESS.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_BRIGHT_EYE_PROCESS_V2_WITH_PUPIL.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_BRIGHT_EYE_PROCESS_V2_WITH_PUPIL.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_FUSE_OFFSET.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_FUSE_OFFSET.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_DEF_CATMULL_ROM.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_DEF_CATMULL_ROM.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_ENABLE_EG_SUPPRESSION.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_ENABLE_EG_SUPPRESSION.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_ENABLE_EG_SUPPRESSION_DEF_CATMULL_ROM.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_ENABLE_EG_SUPPRESSION_DEF_CATMULL_ROM.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_ENABLE_EG_SUPPRESSION_ENABLE_UVMAP.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_ENABLE_EG_SUPPRESSION_ENABLE_UVMAP.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_ENABLE_UVMAP.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_NORMAL_MESH_WARP_Define_ENABLE_UVMAP.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_FUSE_OFFSET_EYE.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_FUSE_OFFSET_EYE.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_FUSE_OFFSET_NORMAL.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_FUSE_OFFSET_NORMAL.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_FUSE_OFFSET_SPLITLR.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_FUSE_OFFSET_SPLITLR.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_WARP_Define_ENABLE_EG_SUPPRESSION.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_WARP_Define_ENABLE_EG_SUPPRESSION.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_WARP_Define_ENABLE_EG_SUPPRESSION_DEF_CATMULL_ROM.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_WARP_Define_ENABLE_EG_SUPPRESSION_DEF_CATMULL_ROM.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_WARP_Define_ENABLE_EG_SUPPRESSION_ENABLE_UVMAP.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_V2_WARP_Define_ENABLE_EG_SUPPRESSION_ENABLE_UVMAP.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_WARP_Define_ENABLE_EG_SUPPRESSION.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_WARP_Define_ENABLE_EG_SUPPRESSION.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_WARP_Define_ENABLE_EG_SUPPRESSION_DEF_CATMULL_ROM.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_WARP_Define_ENABLE_EG_SUPPRESSION_DEF_CATMULL_ROM.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_WARP_Define_ENABLE_EG_SUPPRESSION_ENABLE_UVMAP.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_FACIAL_REFINE_WARP_Define_ENABLE_EG_SUPPRESSION_ENABLE_UVMAP.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_GAUSS_BILATERAL_1D.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_GAUSS_BILATERAL_1D.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_GAUSS_FIX_KERNEL_1D.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_GAUSS_FIX_KERNEL_1D.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_LUMA_TO_ALPHA.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_LUMA_TO_ALPHA.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_MEAN_BLUR.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_MEAN_BLUR.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_MEAN_BOX_2x2.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_MEAN_BOX_2x2.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_NORMAL_LUT_512_512_Define_FRAMEBUFFER_FETCH_ADRENO.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_NORMAL_LUT_512_512_Define_FRAMEBUFFER_FETCH_ADRENO.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_MEANBLUR_1D.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_MEANBLUR_1D.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_MEANBLUR_1D_Define_USE_ALPHA_WEIGHT.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_MEANBLUR_1D_Define_USE_ALPHA_WEIGHT.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_MERGE_MASK.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_MERGE_MASK.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_SIMPLE_PROCESS_ADVANCE_Define_CHANNEL_R.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_SIMPLE_PROCESS_ADVANCE_Define_CHANNEL_R.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_VARIANCE.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_FOGGY_VARIANCE.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_MOISTURIZING_PROCESS_NORMAL.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_MOISTURIZING_PROCESS_NORMAL.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_MOISTURIZING_PROCESS_WITH_MASK_Define_MASK_CHANNEL_TYPE_R.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_MOISTURIZING_PROCESS_WITH_MASK_Define_MASK_CHANNEL_TYPE_R.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_MOISTURIZING_WEIGHT_DATA.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_MOISTURIZING_WEIGHT_DATA.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_TEXTURE_GUIDE.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_TEXTURE_GUIDE.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_TEXTURE_PROCESS_NORMAL.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_RETOUCH_TEXTURE_PROCESS_NORMAL.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_SINGLE_LABEL.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_SINGLE_LABEL.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_SPOTLESS_PROCESS_NORMAL.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_SPOTLESS_PROCESS_NORMAL.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_SPOTLESS_PROCESS_WITH_SKIN_MASK.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_SPOTLESS_PROCESS_WITH_SKIN_MASK.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_WARP_AFFINE.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_WARP_AFFINE.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_WARP_NORMAL.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_WARP_NORMAL.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/OGL_WARP_NORMAL_Define_WARP_TO_ROI.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/OGL_WARP_NORMAL_Define_WARP_TO_ROI.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_P010ToRGB10A2Orientation.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_P010ToRGB10A2Orientation.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_RGB10A2ToP010Orientation.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_RGB10A2ToP010Orientation.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_RGB10A2ToRGB10A2.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_RGB10A2ToRGB10A2.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_RGBA2RGBAUtils.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_RGBA2RGBAUtils.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_RGBA2YUVUtils.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_RGBA2YUVUtils.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_RGBA2YUVUtils_SWAP_UV.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_RGBA2YUVUtils_SWAP_UV.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2RGBAUtils.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2RGBAUtils.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2RGBAUtils_DEHAZE.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2RGBAUtils_DEHAZE.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2RGBAUtils_SWAP_UV.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2RGBAUtils_SWAP_UV.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2RGBAUtils_SWAP_UV_DEHAZE.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2RGBAUtils_SWAP_UV_DEHAZE.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2YUVUtils.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2YUVUtils.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2YUVUtils_SWAP_UV.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_YUV2YUVUtils_SWAP_UV.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/BuildIn/binShaders64/shader_YUVP010ToYUVP010.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/BuildIn/binShaders64/shader_YUVP010ToYUVP010.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Config/config_mode_all.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Config/config_mode_all.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Config/config_mode_front.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Config/config_mode_front.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Config/config_mode_front_video.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Config/config_mode_front_video.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Config/config_mode_rear.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Config/config_mode_rear.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/0_Spotless/FaceMask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/0_Spotless/FaceMask.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/0_Spotless/effect.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/0_Spotless/effect.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothClassical/BeautyMap.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothClassical/BeautyMap.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothClassical/effect_capture.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothClassical/effect_capture.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothClassical/effect_preview.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/1_SkinSmoothClassical/effect_preview.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/2_SkinSmoothRear/FaceMask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/2_SkinSmoothRear/FaceMask.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/2_SkinSmoothRear/effect_capture.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/2_SkinSmoothRear/effect_capture.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/2_SkinSmoothRear/effect_preview.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/Effects/2_SkinSmoothRear/effect_preview.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/mode_front.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/mode_front.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/20_FaceRetouch/mode_rear.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/20_FaceRetouch/mode_rear.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEye/LeftEye.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEye/LeftEye.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEye/RightEye.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEye/RightEye.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEye/effect.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEye/effect.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/effect.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/effect.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/eye_pupil.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/eye_pupil.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/left_eye.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/left_eye.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/right_eye.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/30_BasicRetouch/Effects/0_BrightEyeV3/right_eye.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/30_BasicRetouch/mode_base.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/30_BasicRetouch/mode_base.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/40_FaceStereo/Effects/0_ModeFront/effect_capture.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/40_FaceStereo/Effects/0_ModeFront/effect_capture.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/40_FaceStereo/Effects/0_ModeFront/effect_preview.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/40_FaceStereo/Effects/0_ModeFront/effect_preview.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/40_FaceStereo/Effects/0_ModeFront/xr.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/40_FaceStereo/Effects/0_ModeFront/xr.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/40_FaceStereo/mode_front.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/40_FaceStereo/mode_front.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/50_SkinTone/Effects/0_ModeFront/effect.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/50_SkinTone/Effects/0_ModeFront/effect.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/50_SkinTone/Effects/0_ModeFront/filter.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/50_SkinTone/Effects/0_ModeFront/filter.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/50_SkinTone/mode_front.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/50_SkinTone/mode_front.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/Eyebrow.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/Eyebrow.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/effect_capture.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/effect_capture.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/effect_preview.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/effect_preview.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/sh.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/sh.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/yyy.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/yyy.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/yyz.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/yyz.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/zc.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/60_Makeup/Effects/0_ModeFront/zc.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/60_Makeup/mode_front.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/60_Makeup/mode_front.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeFront/effect_capture.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeFront/effect_capture.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeFront/effect_preview.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeFront/effect_preview.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeFront/eye_refine.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeFront/eye_refine.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeFront/facelift.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/70_FacialRefine/Effects/0_ModeFront/facelift.bin \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/70_FacialRefine/mode_front.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/70_FacialRefine/mode_front.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/effect_list.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/effect_list.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/effect_mode_clear.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/effect_mode_clear.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/effect_mode_front.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/effect_mode_front.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/effect_mode_front_video.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/effect_mode_front_video.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/Effect/effect_mode_rear.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/Effect/effect_mode_rear.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/render/GlobalConfig.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/render/GlobalConfig.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/truesight_config_front.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/truesight_config_front.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/truesight_config_front_video.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/truesight_config_front_video.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/truesight_config_rear.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/truesight_config_rear.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/truesight_param.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/truesight_param.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/resources/truesight_param_debug.json:$(TARGET_COPY_OUT_ODM)/etc/camera/resources/truesight_param_debug.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_cap_model:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_cap_model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_depth_cache:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_depth_cache \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_depth_model:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_depth_model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_depth_policy:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_depth_policy \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_head_cache:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_head_cache \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_head_model:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_head_model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_head_policy:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_head_policy \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_pre_model:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_pre_model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_seg_cache:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_seg_cache \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_seg_model:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_seg_model \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/sg_seg_policy:$(TARGET_COPY_OUT_ODM)/etc/camera/sg_seg_policy \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/20220921.icc:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/20220921.icc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/DSACSettings.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/DSACSettings.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/EcoInfoDynamic.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/EcoInfoDynamic.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/EcoInfoGesture.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/EcoInfoGesture.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/chiofflinesetting.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/chiofflinesetting.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/dualbokehjpegsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/dualbokehjpegsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/dualbokehsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/dualbokehsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/ecoTrdCustomSwitch.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/ecoTrdCustomSwitch.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/frontbokehsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/frontbokehsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/frontsinglesnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/frontsinglesnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/frontsupernightsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/frontsupernightsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/frontsupernightsnapshotjpeg.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/frontsupernightsnapshotjpeg.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/idcardsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/idcardsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/manualsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/manualsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/miuicamerayuv2heic.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/miuicamerayuv2heic.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/miuicamerayuv2jpeg.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/miuicamerayuv2jpeg.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/miviphotographerconfig.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/miviphotographerconfig.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/mivisettings.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/mivisettings.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/mivistreamformat.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/mivistreamformat.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/mivivendorstreamconfig.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/mivivendorstreamconfig.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/normalsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/normalsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/overridesettings.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/overridesettings.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/rearsupernightsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/rearsupernightsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/satburstsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/satburstsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/satsettings.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/satsettings.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/satsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/satsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/satsnapshotjpeg.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/satsnapshotjpeg.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/sdksnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/sdksnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/settings.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/settings.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/superhdsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/superhdsnapshot.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/thirdnormalpreview.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/thirdnormalpreview.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/thirdpartysnapshotjpeg.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/thirdpartysnapshotjpeg.json \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/LG1055-Light.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/LG1055-Light.ttf \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/MiSansVF-Simple-Bold.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/MiSansVF-Simple-Bold.ttf \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/MiSansVF.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/MiSansVF.ttf \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/Roboto-Bold.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/Roboto-Bold.ttf \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/Roboto.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/Roboto.ttf \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_film_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_film_logo.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_logo.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_logo_p3.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_logo_p3.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_poco_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_poco_logo.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0100_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0100_c.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0101.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0101.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0101_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0101_c.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0214.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0214.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0601.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0601.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0815_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0815_c.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_1208_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_1208_c.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_1225.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_1225.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_agra_fort.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_agra_fort.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_amber_fort.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_amber_fort.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_beauty_charm.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_beauty_charm.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_beijing.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_beijing.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_bluesky.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_bluesky.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_buddha.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_buddha.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_cat.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_cat.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_cat_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_cat_c.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_chengdu.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_chengdu.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_chongqing.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_chongqing.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_cloudy.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_cloudy.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_coconut_tree.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_coconut_tree.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_coffee.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_coffee.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_coffee_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_coffee_c.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_cow.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_cow.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_curry.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_curry.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_delicacy.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_delicacy.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_diwali.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_diwali.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_dog.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_dog.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_dog_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_dog_c.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_dussehra.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_dussehra.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_elephant_god.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_elephant_god.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_fleshiness.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_fleshiness.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_flower.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_flower.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_gateway_delhi.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_gateway_delhi.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_gateway_mumbai.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_gateway_mumbai.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_grassplot.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_grassplot.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_great_wall.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_great_wall.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_gu_lang_island.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_gu_lang_island.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_guangzhou.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_guangzhou.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_hang_ya_cave.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_hang_ya_cave.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_hangzhou.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_hangzhou.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_happy_time.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_happy_time.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_holi.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_holi.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_huoguo.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_huoguo.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_kids.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_kids.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_kids_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_kids_c.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_leafs.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_leafs.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_monkey.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_monkey.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_motorcycle.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_motorcycle.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_mount_huang.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_mount_huang.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_namaste.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_namaste.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_nanjing.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_nanjing.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_nightscape.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_nightscape.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_overcast.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_overcast.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_party_time.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_party_time.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_plants.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_plants.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_rakhi.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_rakhi.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_red_fort.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_red_fort.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_republic_day.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_republic_day.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_shanghai.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_shanghai.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_sunrise_sunset.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_sunrise_sunset.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_airplane.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_airplane.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_black_cat.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_black_cat.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_branch_bird.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_branch_bird.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_cable_car.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_cable_car.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_climb.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_climb.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_flying_bird.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_flying_bird.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_leaf.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_leaf.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_1.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_1.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_2.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_2.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_3.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_3.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_4.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_4.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_5.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_5.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_7.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_7.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_8.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_8.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_window.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_window.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_suzhou.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_suzhou.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_suzhou_gardens.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_suzhou_gardens.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_taj_mahal.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_taj_mahal.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_temple_of_heaven.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_temple_of_heaven.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_the_palace_museum.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_the_palace_museum.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_the_potala_palace.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_the_potala_palace.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_the_summer_palace.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_the_summer_palace.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_the_terracotta_army.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_the_terracotta_army.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_tianjin.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_tianjin.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_tutuk.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_tutuk.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_underwater.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_underwater.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_victoria_harbor.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_victoria_harbor.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_west_lake.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_west_lake.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_wuhan.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_wuhan.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_zhang_jia_jie.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_zhang_jia_jie.webp \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomi/watermark/noise_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/noise_logo.png \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xiaomiSceneDetection.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomiSceneDetection.xml \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xmi_slmt_4x_1080p.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/xmi_slmt_4x_1080p.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/camera/xmi_slmt_4x_720p.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/xmi_slmt_4x_720p.dlc \
    vendor/xiaomi/uke/proprietary/odm/etc/display/qdcm_calib_data_xiaomi_o82_36_02_0a_vid_mode_dualdsi_dsc_panel.json:$(TARGET_COPY_OUT_ODM)/etc/display/qdcm_calib_data_xiaomi_o82_36_02_0a_vid_mode_dualdsi_dsc_panel.json \
    vendor/xiaomi/uke/proprietary/odm/etc/display/qdcm_calib_data_xiaomi_o82_42_02_0b_vid_mode_dualdsi_dsc_panel.json:$(TARGET_COPY_OUT_ODM)/etc/display/qdcm_calib_data_xiaomi_o82_42_02_0b_vid_mode_dualdsi_dsc_panel.json \
    vendor/xiaomi/uke/proprietary/odm/etc/init/misensor_camera.rc:$(TARGET_COPY_OUT_ODM)/etc/init/misensor_camera.rc \
    vendor/xiaomi/uke/proprietary/odm/etc/init/vendor.xiaomi.hardware.seaaudio.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.xiaomi.hardware.seaaudio.rc \
    vendor/xiaomi/uke/proprietary/odm/etc/intent_policy/app/com.android.camera.xml.enc:$(TARGET_COPY_OUT_ODM)/etc/intent_policy/app/com.android.camera.xml.enc \
    vendor/xiaomi/uke/proprietary/odm/etc/intent_policy/app/com.tencent.mm.xml.enc:$(TARGET_COPY_OUT_ODM)/etc/intent_policy/app/com.tencent.mm.xml.enc \
    vendor/xiaomi/uke/proprietary/odm/etc/intent_policy/policy.xml.enc:$(TARGET_COPY_OUT_ODM)/etc/intent_policy/policy.xml.enc \
    vendor/xiaomi/uke/proprietary/odm/etc/intent_policy/qcom/policy.xml.enc:$(TARGET_COPY_OUT_ODM)/etc/intent_policy/qcom/policy.xml.enc \
    vendor/xiaomi/uke/proprietary/odm/etc/intent_policy/qcom/sm8650/app/com.android.camera.xml.enc:$(TARGET_COPY_OUT_ODM)/etc/intent_policy/qcom/sm8650/app/com.android.camera.xml.enc \
    vendor/xiaomi/uke/proprietary/odm/etc/intent_policy/qcom/sm8650/app/com.tencent.mm.xml.enc:$(TARGET_COPY_OUT_ODM)/etc/intent_policy/qcom/sm8650/app/com.tencent.mm.xml.enc \
    vendor/xiaomi/uke/proprietary/odm/etc/intent_policy/qcom/sm8650/app/tv.danmaku.bili.xml.enc:$(TARGET_COPY_OUT_ODM)/etc/intent_policy/qcom/sm8650/app/tv.danmaku.bili.xml.enc \
    vendor/xiaomi/uke/proprietary/odm/etc/intent_policy/qcom/sm8650/policy.xml.enc:$(TARGET_COPY_OUT_ODM)/etc/intent_policy/qcom/sm8650/policy.xml.enc \
    vendor/xiaomi/uke/proprietary/odm/etc/sensors/config/palawan_qsh_ble_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/palawan_qsh_ble_0.json \
    vendor/xiaomi/uke/proprietary/odm/etc/thermal-camera.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-camera.conf \
    vendor/xiaomi/uke/proprietary/odm/etc/thermal-gl-camera.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-gl-camera.conf \
    vendor/xiaomi/uke/proprietary/odm/etc/thermal-in-camera.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-in-camera.conf \
    vendor/xiaomi/uke/proprietary/odm/etc/thermal-in-demo-camera.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-in-demo-camera.conf \
    vendor/xiaomi/uke/proprietary/odm/firmware/evass-product.mk:$(TARGET_COPY_OUT_ODM)/firmware/evass-product.mk \
    vendor/xiaomi/uke/proprietary/odm/firmware/film_model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/film_model.tflite \
    vendor/xiaomi/uke/proprietary/odm/firmware/fs19xx.fsm:$(TARGET_COPY_OUT_ODM)/firmware/fs19xx.fsm \
    vendor/xiaomi/uke/proprietary/odm/firmware/glove_model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/glove_model.tflite \
    vendor/xiaomi/uke/proprietary/odm/firmware/ispv4_ddr_train:$(TARGET_COPY_OUT_ODM)/firmware/ispv4_ddr_train \
    vendor/xiaomi/uke/proprietary/odm/firmware/ispv4_firmware:$(TARGET_COPY_OUT_ODM)/firmware/ispv4_firmware \
    vendor/xiaomi/uke/proprietary/odm/firmware/network_binary_2304.nb:$(TARGET_COPY_OUT_ODM)/firmware/network_binary_2304.nb \
    vendor/xiaomi/uke/proprietary/odm/firmware/novatek_nt36532_o82_fw_csot.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_o82_fw_csot.bin \
    vendor/xiaomi/uke/proprietary/odm/firmware/novatek_nt36532_o82_fw_tm.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_o82_fw_tm.bin \
    vendor/xiaomi/uke/proprietary/odm/firmware/novatek_nt36532_o82_mp_csot.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_o82_mp_csot.bin \
    vendor/xiaomi/uke/proprietary/odm/firmware/novatek_nt36532_o82_mp_tm.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_o82_mp_tm.bin \
    vendor/xiaomi/uke/proprietary/odm/firmware/nvt_run_selftest_get_result_data_sample.bat:$(TARGET_COPY_OUT_ODM)/firmware/nvt_run_selftest_get_result_data_sample.bat \
    vendor/xiaomi/uke/proprietary/odm/firmware/o82_nova_thp_config.ini:$(TARGET_COPY_OUT_ODM)/firmware/o82_nova_thp_config.ini \
    vendor/xiaomi/uke/proprietary/odm/firmware/o82_nova_tm_thp_config.ini:$(TARGET_COPY_OUT_ODM)/firmware/o82_nova_tm_thp_config.ini \
    vendor/xiaomi/uke/proprietary/odm/firmware/palm_check.tflite:$(TARGET_COPY_OUT_ODM)/firmware/palm_check.tflite \
    vendor/xiaomi/uke/proprietary/odm/firmware/water_check.tflite:$(TARGET_COPY_OUT_ODM)/firmware/water_check.tflite \
    vendor/xiaomi/uke/proprietary/odm/lib64/camera/com.qti.sensormodule.o82_aac_ov08d10_front_i.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.o82_aac_ov08d10_front_i.bin \
    vendor/xiaomi/uke/proprietary/odm/lib64/camera/com.qti.sensormodule.o82_ofilm_ov13b10_wide_i.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.o82_ofilm_ov13b10_wide_i.bin \
    vendor/xiaomi/uke/proprietary/odm/lib64/camera/com.qti.tuned.o82_aac_ov08d10_front_i.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.o82_aac_ov08d10_front_i.bin \
    vendor/xiaomi/uke/proprietary/odm/lib64/camera/com.qti.tuned.o82_ofilm_ov13b10_wide_i.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.o82_ofilm_ov13b10_wide_i.bin \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/click.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/click.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/double_click.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/double_click.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/heavy_click.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/heavy_click.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/pop.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/pop.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/reserved_1.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_1.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/reserved_2.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_2.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/reserved_3.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_3.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/reserved_4.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_4.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/reserved_5.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_5.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/reserved_6.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_6.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/reserved_7.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_7.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/reserved_8.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_8.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/texture_tick.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/texture_tick.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/thud.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/thud.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/acdbdata/haptics_data/tick.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/tick.pcm \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/102_SummerDay.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/102_SummerDay.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/103_Fantasy.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/103_Fantasy.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/104_Meet.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/104_Meet.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/105_WindSing.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/105_WindSing.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/106_Lost.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/106_Lost.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/107_Central.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/107_Central.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/108_NorthernEurope.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/108_NorthernEurope.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/109_Rome.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/109_Rome.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/110_BlackGold.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/110_BlackGold.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/111_GreenOrange.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/111_GreenOrange.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/112_CyberPunk.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/112_CyberPunk.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/113_BlackIce.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/113_BlackIce.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/121_Bleach.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/121_Bleach.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/122_Thriller.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/122_Thriller.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/123_TealOrange.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/123_TealOrange.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/124_JapaneseStyle.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/124_JapaneseStyle.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/125_Latin.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/125_Latin.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/126_Fantasy2.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/126_Fantasy2.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/127_Creamy.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/127_Creamy.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/128_Sepia.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/128_Sepia.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/129_Vivid.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/129_Vivid.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/130_Natural.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/130_Natural.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/131_Monochrome.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/131_Monochrome.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/132_MonochromeHighContrast.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/132_MonochromeHighContrast.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/133_MonochromeBrown.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/133_MonochromeBrown.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/134_MonochromeBlue.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/134_MonochromeBlue.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/135_Classical.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/135_Classical.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/136_Filene.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/136_Filene.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/137_GreenNight.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/137_GreenNight.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/138_LiteratureAndArt.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/138_LiteratureAndArt.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/139_OrangeHoney.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/139_OrangeHoney.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/140_Romance.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/140_Romance.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/141_FR500.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/141_FR500.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/142_FE250.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/142_FE250.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/143_RedLantern.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/143_RedLantern.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/144_RedHero.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/144_RedHero.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/145_TactileBlackWhite.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/145_TactileBlackWhite.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/146_TactileGreen.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/146_TactileGreen.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/147_Neutral.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/147_Neutral.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/148_Mild.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/148_Mild.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/149_LilyWhite.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/149_LilyWhite.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/150_Bright.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/150_Bright.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/151_Fresh.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/151_Fresh.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/152_Limpid.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/152_Limpid.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/153_KC64.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/153_KC64.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/154_V250.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/154_V250.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/155_H400.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/155_H400.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/156_ColdWhite.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/156_ColdWhite.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/157_Native.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/157_Native.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/158_BWClassical.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/158_BWClassical.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/159_Flowers.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/159_Flowers.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/160_Vivid1.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/160_Vivid1.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/161_Monsoon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/161_Monsoon.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/162_Natural1.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/162_Natural1.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/163_Slack.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/163_Slack.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/164_Kyoto.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/164_Kyoto.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/165_OldAlley.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/165_OldAlley.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/166_Reversal.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/166_Reversal.png \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/bokehParams.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bokehParams.json \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/cameraopt_perf.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cameraopt_perf.json \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/cameraopt_vendor.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cameraopt_vendor.json \
    vendor/xiaomi/uke/proprietary/vendor/etc/camera/model_front_mibokeh_video.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front_mibokeh_video.dlc \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/bitmlconfig.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/bitmlconfig.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/bitmlconfig_sm8635.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/bitmlconfig_sm8635.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/camxfl115indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl115indices.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/camxfl300v1indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v1indices.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/camxfl300v2indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v2indices.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/camxflcustom300indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxflcustom300indices.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/fdconfigsecure.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigsecure.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/xiaomi/uke/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    com.mi.node.dlengine \
    com.mi.node.mawcommon \
    com.mi.node.mawsaliency \
    com.mi.node.mimovie \
    com.mi.node.mioisverify \
    com.mi.node.videobokeh \
    com.mi.node.videofilter \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.hwcfg.bps \
    com.qti.hwcfg.ife \
    com.qti.hwcfg.ipe \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.evadepth \
    com.qti.node.evs \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.hdr10plushist \
    com.qti.node.hdr10plusmeta \
    com.qti.node.itofpreprocess \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.mlinference \
    com.qti.node.muxer \
    com.qti.node.pixelstats \
    com.qti.node.seg \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afc \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbr \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.roimixer \
    com.qti.stats.roimixerlib \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.xiaomi.node.gme \
    com.xiaomi.node.misv2 \
    com.xiaomi.node.misv3 \
    libcamxevainterface \
    libdepthmapwrapper_itof \
    libdepthmapwrapper_secure \
    libmicamvendorcustom \
    camera.qcom.sm8650 \
    vendor.xiaomi.sensor.camera-V1-ndk \
    com.qti.actuator.o82_ofilm_ov13b10_cn3927v_wide_i_actuator \
    com.qti.eeprom.o82_aac_ov08d10_gt24p64e_front_i_eeprom \
    com.qti.eeprom.o82_ofilm_ov13b10_bl24sa64_wide_i_eeprom \
    com.qti.sensor.o82_aac_ov08d10_front_i \
    com.qti.sensor.o82_ofilm_ov13b10_wide_i \
    com.jigan.node.videobokeh \
    com.mi.node.aiasd \
    com.mi.node.facealign \
    com.mi.node.facecenter \
    com.mi.node.gpu3rd \
    com.mi.node.realtimebokeh \
    com.mi.node.rearvideo \
    com.mi.node.singlebokeh \
    com.mi.node.tsskinbeautifier \
    com.mi.node.videonight \
    com.qti.node.intelligentfocus \
    com.qti.node.ldc \
    libchxlogicalcameratable \
    com.xiaomi.plugin.GestureEffects \
    com.xiaomi.plugin.anchor \
    com.xiaomi.plugin.arcsoftsll \
    com.xiaomi.plugin.depurple \
    com.xiaomi.plugin.filter \
    com.xiaomi.plugin.frontbokeh \
    com.xiaomi.plugin.gainmap \
    com.xiaomi.plugin.gainmapPostProc \
    com.xiaomi.plugin.hdr \
    com.xiaomi.plugin.jpegrAggr \
    com.xiaomi.plugin.ldc \
    com.xiaomi.plugin.mawaiie \
    com.xiaomi.plugin.memcpy \
    com.xiaomi.plugin.miaideblur \
    com.xiaomi.plugin.movieeffect \
    com.xiaomi.plugin.offlinepostproc \
    com.xiaomi.plugin.pixman \
    com.xiaomi.plugin.portraitrepair \
    com.xiaomi.plugin.simulation \
    com.xiaomi.plugin.sr \
    com.xiaomi.plugin.supermoon \
    com.xiaomi.plugin.swflip \
    com.xiaomi.plugin.swjpegencode \
    com.xiaomi.plugin.tsskinbeautifier \
    com.xiaomi.plugin.watermark \
    com.xiaomi.zsl.aihighlight \
    com.xiaomi.zsl.bokehrawhdr \
    com.xiaomi.zsl.bokehsmartae \
    com.xiaomi.zsl.default \
    com.xiaomi.zsl.ell \
    com.xiaomi.zsl.hdr \
    com.xiaomi.zsl.leica \
    com.xiaomi.zsl.mfnr \
    com.xiaomi.zsl.motion \
    com.xiaomi.zsl.nightmotion \
    com.xiaomi.zsl.nightmotionzslbanding \
    com.xiaomi.zsl.sr \
    vendor.xiaomi.hardware.seaaudio-V1-ndk \
    misensor_camera.xml \
    vendor.xiaomi.hardware.seaaudio.xml \
    audio-factory-test \
    misensor_camera \
    vendor.xiaomi.hardware.seaaudio-service \
    ispv4_ddr_boot \
    ispv4_driver_test \
    ispv4_power_ctrl \
    ispv4_release_cpu \
    ispv4_sensor_ctl \
    ispv4_setpcie_speed \
    ispv4_spi_rw \
    ispv4_spi_st \
    ispv4_utils_lspci \
    ispv4_utils_setpci \
    ispv4_utils_xxd
